quarkiverse/quarkus-artemis

test-framework/pom.xml

This dependency is gone from quarkus-test-common and is apparently required:
```
2022-03-29T05:47:57.3752129Z Caused by: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: javax/json/JsonValue
2022-03-29T05:47:57.3752647Z 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
2022-03-29T05:47:57.3753166Z 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
2022-03-29T05:47:57.3753658Z 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
2022-03-29T05:47:57.3754144Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-03-29T05:47:57.3754632Z 	at …
```

Add quarkus-jsonp dependency to quarkus-test-artemis

---

jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsProcessor.java
jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsWrapper.java

We don't need to have `transactionManager` in wrapper since it should be obtained by the other extensions such as `messaginghub-pooled-jms` if it decides to add transaction manager integration.

Remove transaction manager in wrapper

---

core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ArtemisDevServicesBuildTimeConfig.java
core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
integration-tests/core/src/test/java/io/quarkus/it/artemis/DevServiceArtemisEnabled.java

- remove `queues` property and add `extraArgs` which could be passed to container as `AMQ_EXTRA_ARGS`
- introduce `ArtemisContainer` to support fixedExposedPort

Improve Artemis DevService

---

core/runtime/src/main/java/io/quarkus/artemis/core/runtime/health/ServerLocatorHealthCheck.java
jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/health/ConnectionFactoryHealthCheck.java

In the health checks, get the default ServerLocator/ConnectionFactory through the @Default annotation instead of through the @Identifier annotation.
Resolves #112 .

#112: Use @Default to get default ServerLocator/ConnectionFactory in healtch cheks

---

.github/workflows/build.yml

Issue: https://github.com/quarkiverse/quarkus-artemis/issues/156

#156: remove package-phase from populate-cache-job

---

docs/modules/ROOT/pages/index.adoc

During the update to Quarkus 3 and quarkus-artemis 3, I struggled a while, having no `ConnectionFactory` in my application. Eventually I saw the parts of the documentation further downwards, where it explained that some build-time configuration is now required.
I therefore propose to put this important piece of information much more prominently, so that people will more easily see it, we safe them some investigation time, and improve the overall development experience. 🙂

documentation: important notice about build-time config

---

core/runtime/pom.xml

- Caused by https://github.com/quarkusio/quarkus/pull/34145

Use `graal-sdk` instead of `svm`

---

docs/modules/ROOT/pages/index.adoc

Docs: Reword XA-section

---

integration-tests/core/common/src/main/java/io/quarkus/it/artemis/core/common/ArtemisCoreConsumerManager.java
integration-tests/core/common/src/main/java/io/quarkus/it/artemis/core/common/ArtemisCoreProducerManager.java
integration-tests/jms/common/src/main/java/io/quarkus/it/artemis/jms/common/ArtemisJmsConsumerManager.java
integration-tests/jms/common/src/main/java/io/quarkus/it/artemis/jms/common/ArtemisJmsXaConsumerManager.java
integration-tests/jms/common/src/test/java/io/quarkus/it/artemis/jms/common/ArtemisJmsHelper.java
integration-tests/jms/with-default-and-external/src/main/java/io/quarkus/it/artemis/jms/withdefaultandexternal/ArtemisEndpoint.java
integration-tests/jms/with-default-and-external/src/main/java/io/quarkus/it/artemis/jms/withdefaultandexternal/BeanProducer.java
integration-tests/jms/with-default-and-external/src/test/java/io/quarkus/it/artemis/jms/withdefaultandexternal/BaseArtemisConsumerTest.java
integration-tests/jms/with-default-and-external/src/test/java/io/quarkus/it/artemis/jms/withdefaultandexternal/embedded/EmbeddedConsumerTest.java
integration-tests/jms/with-default-change-url/src/main/java/io/quarkus/it/artemis/jms/withdefault/changeurl/ArtemisEndpoint.java
integration-tests/jms/with-default-change-url/src/main/java/io/quarkus/it/artemis/jms/withdefault/changeurl/BeanProducer.java
integration-tests/jms/with-default-change-url/src/test/java/io/quarkus/it/artemis/jms/withdefault/changeurl/embedded/EmbeddedConsumerTest.java
integration-tests/jms/with-default/src/main/java/io/quarkus/it/artemis/jms/withdefault/ArtemisEndpoint.java
integration-tests/jms/with-default/src/main/java/io/quarkus/it/artemis/jms/withdefault/BeanProducer.java
integration-tests/jms/with-default/src/test/java/io/quarkus/it/artemis/jms/withdefault/BaseArtemisConsumerTest.java
integration-tests/jms/with-external/src/main/java/io/quarkus/it/artemis/jms/withexternal/ArtemisEndpoint.java
integration-tests/jms/with-external/src/main/java/io/quarkus/it/artemis/jms/withexternal/BeanProducer.java
integration-tests/jms/with-external/src/test/java/io/quarkus/it/artemis/jms/withexternal/embedded/EmbeddedConsumerTest.java
integration-tests/jms/without-default/src/main/java/io/quarkus/it/artemis/jms/withoutdefault/ArtemisEndpoint.java
integration-tests/jms/without-default/src/main/java/io/quarkus/it/artemis/jms/withoutdefault/BeanProducer.java
integration-tests/jms/without-default/src/test/java/io/quarkus/it/artemis/jms/withoutdefault/BaseArtemisConsumerTest.java

Resolves [#319](https://github.com/quarkiverse/quarkus-artemis/issues/319)

Add MessageConsumer XA Commit and Rollback tests for artemis-jms

---

integration-tests/camel-jms/common/src/test/java/io/quarkus/it/artemis/camel/jms/common/BaseSendAndReceiveTest.java
integration-tests/common/src/test/java/io/quarkus/it/artemis/common/ArtemisHealthCheckHelper.java
integration-tests/core/common/src/main/java/io/quarkus/it/artemis/core/common/ArtemisCoreConsumerManager.java
integration-tests/core/common/src/main/java/io/quarkus/it/artemis/core/common/ArtemisCoreProducerManager.java
integration-tests/core/common/src/test/java/io/quarkus/it/artemis/core/common/ArtemisCoreHelper.java
integration-tests/jms/common/src/main/java/io/quarkus/it/artemis/jms/common/ArtemisJmsConsumerManager.java
integration-tests/jms/common/src/main/java/io/quarkus/it/artemis/jms/common/ArtemisJmsXaConsumerManager.java
integration-tests/jms/common/src/test/java/io/quarkus/it/artemis/jms/common/ArtemisJmsHelper.java

- When no message can be received, return null
- Where possible, rely on RestAssured

Cleanup integration tests

---

ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java

This supports additional activation spec properties mentioned in #400 
* messageSelector
* subscriptionDurability
* subscriptionName
* shareSubscriptions

support additional activation specs in the config

---

docs/modules/ROOT/pages/quarkus-artemis-ra.adoc
ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java

This allows setting the client id at the adapter level through the application.properties:
```
quarkus.ironjacamar.artemis.ra.config.client-id=Quarkus
```
Closes #427

Allow configuring a client id at the adapter level

---

.github/dependabot.yml

This might prevent https://github.com/dependabot/dependabot-core/issues/9432

Instead of only ignore io.quarkus:quarkus-bom, ignore io.quarkus:*

---

.github/dependabot.yml

All prior versions need to stay on jandex 3.1.x.

The update to jandex 3.2.0 is scheduled for quarkus 3.12.

---

.github/workflows/build.yml
.github/workflows/pr-comment.yml
.github/workflows/pr-report.yml

Resolves #623.
Please do not be surprised. For the changes to take full effect, the workflows `pr-comment.yml` and `pr-report.yml` need to be on the default branch.
The final result will be virtually indistinguishable from the current behaviour, see https://github.com/turing85/quarkus-artemis/pull/2#issuecomment-2339250938

#623: Restructure pipeline so PR runs from forks succeed.

---

core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java

Fix NullPointerException due to missing schema

---

bom/pom.xml
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/quarkus-artemis-jms.adoc
docs/modules/ROOT/pages/quarkus-artemis-ra.adoc

Also changed the `quarkus.version` into `quarkus-version` to align with Quarkus itself. And fix the `$` of `quarkus-artemis-version`.
Resolves #437

Use and document Artemis BOM, fixes #437

---

docs/modules/ROOT/pages/quarkus-artemis-jms.adoc
docs/modules/ROOT/pages/quarkus-artemis-ra.adoc

Prevent version strings in quarkus-artemis-jms.adoc from being replaced with the predefined attributes.

---

core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
docs/modules/ROOT/pages/includes/quarkus-artemis-core_quarkus.artemis.adoc

This also means switching from quay.io/artemiscloud to quay.io/arkmq-org.

Bump artemis-image from 2.38.0 to 2.39.0.

---

core/deployment/pom.xml
core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ArtemisCoreProcessor.java

Add native support for HornetQ

---

core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java
core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java

While using this Project and its provided Dev-Services I noticed that the Artemis web-ui (8161) is not exposed.
Since this is a feature I would find convenient I decided to build a version that would support it 
Other Dev-Services (Quarkus AMQP) do expose the Web-Ui, I was therefore curios if maybe this Project also has an Interested in adding the feature into its code base as well.
This PR now exposes the Artemis-Web-Ui (Port 8161) per default at a random port. 
Using the optional "web-ui-port" property a fixed port on which to expose the Ui can be defined.
- Add the Optional Parameter `webUiPort` into the `ArtemisDevServicesBuildTimeConfig`
- Add `ARTEMIS_WEB_UI_PORT` to the exposed ports when building the `ArtemisContainer`
- Add the fixed exposed port (if set) when the  configuration …

Add support for exposing the Artemis Web-Ui

---

docs/modules/ROOT/pages/quarkus-artemis-ra.adoc
ra/deployment/src/main/java/io/quarkus/artemis/jms/ra/deployment/DevServicesArtemisProcessor.java

This brings some support for compose dev service in artemis jms RA.
I left 3 `TODO` with open questions. I would like your advice @ozangunalp 
I used apicurio as an example to bring those modifications from this [commit](https://github.com/quarkusio/quarkus/pull/46848/files#diff-a95c1e07d280f4aa2a52da9dc054fd1941c07ec5020ba046b0c75052d1ba7314)
I have tested with:
```
name: my-app
services:
artemis:
image: quay.io/arkmq-org/activemq-artemis-broker:artemis.2.40.0
ports:
- "61616"
environment:
AMQ_USER: admin
AMQ_PASSWORD: admin
AMQ_EXTRA_ARGS: --no-autotune --mapped --no-fsync
labels:
io.quarkus.devservices.compose.wait_for.ports.disable: true
io.quarkus.devservices.compose.wait_for.logs: .*AMQ241004.*
```
this works fine. if the compose container is started, it gets picked up. if not, a …

Support Compose DevService
