quarkiverse/quarkus-artemis

- core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ArtemisCoreProcessor.java
> Don't produce a feature for Artemis Core

- integration-tests/jms/src/main/java/io/quarkus/it/artemis/ArtemisConsumerManager.java
- integration-tests/jms/src/main/java/io/quarkus/it/artemis/ArtemisProducerManager.java
- integration-tests/jms/src/test/java/io/quarkus/it/artemis/ArtemisHelper.java
Session is a JMS 1.x API, they also have the same constants on JMSContext which is a JMS 2.x API.
> Use JMSContext for session mode

- .github/project.yml
> Release 1.3.0

- docs/modules/ROOT/pages/index.adoc
> #91: improved documentation

- core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
See discussion in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Listing.20unlisted.20extensions/near/311250073
> Make artemis-core listed

- .github/workflows/build.yml
> Rewrite get-date pipeline step to remove warning

- .github/workflows/build.yml
- pom.xml
- reordered properties in root pom
- added capability to run pipelines manually
- 1st step now only downloads dependencies, 2nd job runs unconditionally
> Improve pipeline

- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java
- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/health/ArtemisHealthSupportRecorder.java
- docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
- jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
> replaced anonymous classes with lambdas

- .github/workflows/build.yml
- .github/workflows/release.yml
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
> Add maven wrappers

- build-parent/pom.xml
> Remove io.quarkus:quarkus-jms-spi-deployment in build-parent

- .github/workflows/build.yml
- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsProcessor.java
- jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
- Update turing85/publish-report from 1.0.6 to 1.0.8
Resolves #230
> #230: Initialize ConnectionFactory at application startup

- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
- docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
Upgrade artemis image from quay.io/artemiscloud/activemq-artemis-broker:1.0.18 to quay.io/artemiscloud/activemq-artemis-broker:artemis.2.30.0
> Upgrade artemis image

- docs/antora.yml
- This fixes the issue while building https://github.com/quarkiverse/quarkiverse-docs/pull/112
> Update doc version

- pom.xml
> Fix #344 exclude integration-tests when doing release

- core/runtime/pom.xml
- integration-tests/camel-jms/common/pom.xml
- integration-tests/common-parent/pom.xml
- integration-tests/common/pom.xml
- integration-tests/core/common/pom.xml
- integration-tests/jms/common/pom.xml
> Fix #347 to add commons-logging-jboss-logging

- bom/pom.xml
> Manage artemis protocols in our BOM

- docs/modules/ROOT/pages/index.adoc
> Fix #365 to add index.adoc

- .github/dependabot.yml
See https://github.com/quarkiverse/quarkus-artemis/pull/405#issuecomment-1934233670
> For branch 2.x, suppress quariverse-partent >= 16

- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
- docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
Upgrade image quay.io/artemiscloud/activemq-artemis-broker from `artemis.2.32.0` to `artemis.2.33.0`
> Upgrade image quay.io/artemiscloud/activemq-artemis-broker

- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
Upgrade default artemis image quay.io/artemiscloud/activemq-artemis-broker from artemis.2.34.0 to artemis.2.35.0
> Upgrade default artemis image

- docs/modules/ROOT/pages/quarkus-artemis-jms.adoc
Move versions that reached EOL in a collapsible element
> Reorder EOL Tables: newest version to oldest version

- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
- Upgrade maven wrapper from 3.1.2 to 3.3.2
- Upgrade maven from 3.8.7 to 3.9.8
> Upgrade maven

- ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java
> Repeat `NettyConnectorFactory` for each host

- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
- docs/modules/ROOT/pages/includes/quarkus-artemis-core_quarkus.artemis.adoc
Bump artemis image from quay.io/artemiscloud/activemq-artemis-broker:artemis.2.37.0 to quay.io/artemiscloud/activemq-artemis-broker:artemis.2.38.0
> Bump artemis image

- core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java
> Switch from GlobalDevServicesConfig to DevServicesConfig

- core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
- ra/deployment/src/main/java/io/quarkus/artemis/jms/ra/deployment/DevServicesArtemisProcessor.java
- ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/runtime/ArtemisDevServicesBuildTimeConfig.java
Fixes https://github.com/quarkiverse/quarkus-artemis/issues/822
> Align images between core and ra devservices
